/**
 * Backtest-related types for frontend
 * Re-exports from @trading25/shared and adds frontend-specific types
 */

// Re-export types from shared package
export type {
  BacktestJobResponse,
  BacktestRequest,
  BacktestResultResponse,
  BacktestResultSummary,
  DefaultConfigResponse,
  DefaultConfigUpdateRequest,
  DefaultConfigUpdateResponse,
  EvolutionHistoryItem,
  GenerateResultItem,
  HealthResponse,
  HtmlFileContentResponse,
  HtmlFileDeleteResponse,
  HtmlFileInfo,
  HtmlFileListResponse,
  HtmlFileMetrics,
  HtmlFileRenameRequest,
  HtmlFileRenameResponse,
  ImprovementItem,
  JobStatus,
  LabEvolveRequest,
  LabEvolveResult,
  LabGenerateRequest,
  LabGenerateResult,
  LabImproveRequest,
  LabImproveResult,
  LabJobResponse,
  LabOptimizeRequest,
  LabOptimizeResult,
  LabResultData,
  LabSSEEvent,
  LabType,
  OptimizationGridConfig,
  OptimizationGridListResponse,
  OptimizationGridSaveRequest,
  OptimizationGridSaveResponse,
  OptimizationHtmlFileContentResponse,
  OptimizationHtmlFileInfo,
  OptimizationHtmlFileListResponse,
  OptimizationJobResponse,
  OptimizationRequest,
  OptimizeTrialItem,
  SignalCategory,
  SignalAttributionJobResponse,
  SignalAttributionLooResult,
  SignalAttributionMetrics,
  SignalAttributionRequest,
  SignalAttributionResult,
  SignalAttributionResultResponse,
  SignalAttributionShapleyMeta,
  SignalAttributionShapleyResult,
  SignalAttributionSignalResult,
  SignalAttributionTiming,
  SignalAttributionTopNScore,
  SignalAttributionTopNSelection,
  SignalDefinition,
  SignalFieldDefinition,
  SignalReferenceResponse,
  StrategyDeleteResponse,
  StrategyDetailResponse,
  StrategyDuplicateRequest,
  StrategyDuplicateResponse,
  StrategyListResponse,
  StrategyMetadata,
  StrategyRenameRequest,
  StrategyRenameResponse,
  StrategyUpdateRequest,
  StrategyUpdateResponse,
  StrategyValidationRequest,
  StrategyValidationResponse,
} from '@trading25/clients-ts/backtest';

// Frontend-specific types
export type BacktestSubTab = 'runner' | 'results' | 'attribution' | 'strategies' | 'status' | 'dataset' | 'lab';
