/**
 * Backtest Client Module
 */

export { BacktestApiError, BacktestClient } from './BacktestClient.js';
export { LabResultDataSchema, validateLabResultData } from './lab-result-schemas.js';
export type {
  BacktestClientConfig,
  BacktestJobResponse,
  BacktestRequest,
  BacktestResultResponse,
  BacktestResultSummary,
  DailyValuationDataPoint,
  DefaultConfigResponse,
  DefaultConfigUpdateRequest,
  DefaultConfigUpdateResponse,
  EvolutionHistoryItem,
  FundamentalDataPoint,
  FundamentalsComputeRequest,
  FundamentalsComputeResponse,
  FundamentalsPeriodType,
  GenerateResultItem,
  HandleZeroDivision,
  HealthResponse,
  HtmlFileContentResponse,
  HtmlFileDeleteResponse,
  HtmlFileInfo,
  HtmlFileListResponse,
  HtmlFileMetrics,
  HtmlFileRenameRequest,
  HtmlFileRenameResponse,
  ImprovementItem,
  JobStatus,
  LabEvolveRequest,
  LabEvolveResult,
  LabGenerateRequest,
  LabGenerateResult,
  LabImproveRequest,
  LabImproveResult,
  LabJobResponse,
  LabOptimizeRequest,
  LabOptimizeResult,
  LabResultData,
  LabSSEEvent,
  LabType,
  OHLCVRecord,
  OHLCVResampleRequest,
  OHLCVResampleResponse,
  OptimizationGridConfig,
  OptimizationGridListResponse,
  OptimizationGridSaveRequest,
  OptimizationGridSaveResponse,
  OptimizationHtmlFileContentResponse,
  OptimizationHtmlFileInfo,
  OptimizationHtmlFileListResponse,
  OptimizationJobResponse,
  OptimizationRequest,
  OptimizeTrialItem,
  RelativeOHLCOptions,
  SignalCategory,
  SignalDefinition,
  SignalFieldDefinition,
  SignalReferenceResponse,
  StrategyDeleteResponse,
  StrategyDetailResponse,
  StrategyDuplicateRequest,
  StrategyDuplicateResponse,
  StrategyListResponse,
  StrategyMetadata,
  StrategyRenameRequest,
  StrategyRenameResponse,
  StrategyUpdateRequest,
  StrategyUpdateResponse,
  StrategyValidationRequest,
  StrategyValidationResponse,
  Timeframe as BtTimeframe,
} from './types.js';
